project_name: steadybit-debug
before:
  hooks:
    - go mod download
release:
  prerelease: "false"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x
    goarm:
      - "7"
    flags:
      - -trimpath
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: steadybit-debug
    tap:
      owner: steadybit
      name: homebrew-steadybit-debug
    commit_author:
      name: ansgarschulte
      email: ansgar@steadybit.com
    folder: Formula
    homepage: https://github.com/steadybit/steadybit-debug
    description: Tool to gather debugging information from (on-premise) Steadybit platforms and agents